# Generated by Django 3.1.1 on 2020-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=55)),
                ('author', models.CharField(max_length=55)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
