# Generated by Django 3.1.1 on 2020-12-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('message', models.TextField()),
            ],
        ),
    ]
